import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-background": "#1b1c1c",
        "surface-container": "#f0eded",
        "on-tertiary": "#ffffff",
        surface: "#fcf9f8",
        "on-secondary-container": "#7a443a",
        "secondary-fixed-dim": "#feb4a7",
        "error-container": "#ffdad6",
        "on-primary-container": "#758dd5",
        background: "#fcf9f8",
        "surface-tint": "#435b9f",
        "on-secondary": "#ffffff",
        "surface-dim": "#dcd9d9",
        "on-surface-variant": "#444650",
        "primary-fixed-dim": "#b3c5ff",
        "on-tertiary-fixed-variant": "#384953",
        "surface-container-high": "#eae7e7",
        primary: "#00113a",
        "on-secondary-fixed-variant": "#6c382f",
        "tertiary-container": "#1a2b34",
        "on-surface": "#1b1c1c",
        "primary-container": "#002366",
        "inverse-primary": "#b3c5ff",
        "surface-variant": "#e4e2e1",
        secondary: "#884f45",
        "surface-container-highest": "#e4e2e1",
        "on-secondary-fixed": "#360e08",
        "on-error-container": "#93000a",
        "surface-bright": "#fcf9f8",
        "on-primary": "#ffffff",
        outline: "#757682",
        "inverse-surface": "#303030",
        "outline-variant": "#c5c6d2",
        "on-error": "#ffffff",
        "secondary-fixed": "#ffdad4",
        "surface-container-lowest": "#ffffff",
        "secondary-container": "#feb4a7",
        tertiary: "#05161f",
        "on-tertiary-container": "#81929d",
        error: "#ba1a1a",
        "tertiary-fixed-dim": "#b7c9d5",
        "tertiary-fixed": "#d3e5f1",
        "on-primary-fixed-variant": "#2a4386",
        "surface-container-low": "#f6f3f2",
        "on-primary-fixed": "#00174a",
        "on-tertiary-fixed": "#0c1e26",
        "primary-fixed": "#dbe1ff",
        "inverse-on-surface": "#f3f0f0",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      spacing: {
        unit: "4px",
        gutter: "24px",
        "margin-desktop": "80px",
        "section-gap": "120px",
        "margin-mobile": "20px",
      },
      fontFamily: {
        "body-lg": ["var(--font-manrope)", "Manrope", "sans-serif"],
        "label-mono": ["var(--font-jetbrains-mono)", "JetBrains Mono", "monospace"],
        "body-md": ["var(--font-manrope)", "Manrope", "sans-serif"],
        "display-lg-mobile": ["var(--font-libre-caslon)", "Libre Caslon Text", "serif"],
        "headline-md": ["var(--font-libre-caslon)", "Libre Caslon Text", "serif"],
        "display-lg": ["var(--font-libre-caslon)", "Libre Caslon Text", "serif"],
      },
      fontSize: {
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
        "label-mono": ["13px", { lineHeight: "1.0", letterSpacing: "0.05em", fontWeight: "500" }],
        "body-md": ["16px", { lineHeight: "1.6", fontWeight: "400" }],
        "display-lg-mobile": ["40px", { lineHeight: "1.2", letterSpacing: "-0.01em", fontWeight: "700" }],
        "headline-md": ["32px", { lineHeight: "1.3", fontWeight: "600" }],
        "display-lg": ["64px", { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "700" }],
      },
    },
  },
  plugins: [require("@tailwindcss/forms")],
};
export default config;
